# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-14 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='section_1_image',
        ),
        migrations.AddField(
            model_name='client',
            name='client_image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/clients/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='name', max_length=255, verbose_name='Client Name'),
            preserve_default=False,
        ),
    ]
