# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-14 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171013_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('large', 'Larger')], default='normal', max_length=256),
            preserve_default=False,
        ),
    ]
