# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171013_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('employee_image', models.ImageField(default='media/None/no-img.jpg', upload_to='media/employees/', verbose_name='Image')),
                ('employee_type', models.CharField(choices=[('leadership', 'Leadership'), ('operations', 'Operations'), ('catalog', 'Catalog'), ('account_management', 'Account Management'), ('development', 'Development'), ('marketing', 'Marketing'), ('support', 'Support')], max_length=256)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
