# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_title',
            field=models.CharField(default='Title', max_length=255, verbose_name='Employee Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=255, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('operations', 'Operations'), ('catalog', 'Catalog'), ('account_management', 'Account Management'), ('development', 'Development'), ('marketing', 'Marketing'), ('support', 'Support')], max_length=256),
        ),
    ]
